name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install and Build 🔧
      run: sudo apt-get install --allow-downgrades <package_name>

    - name: Deploy
      run: <deploy_command>